apiVersion: apps/v1
kind: Deployment
metadata:
 name: red
spec:
 replicas: 3
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
   containers:
   - name: nginx
     image: nginx
     ports:
     - containerPort: 80
